[package]
name = "saffron-lang"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "saffron-lang"
path = "src/main.rs"

[dependencies]
tower-lsp = "0.20.0"
tokio = { version = "1", features = ["full"] }
nom = "7"
nom_locate = "4.2.0"